### ISSUE TITLE
SMAStudiovNext Compiles, but will not run - error listed in log.

### ISSUE THREAD

**Issue by PatrickGallucci** [icanos/SMAStudio#15]
Log Name:      Application
Source:        .NET Runtime
Date:          3/8/2016 12:16:53 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TX60LP519681
Description:
Application: SMAStudiovNext.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Gemini.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at Gemini.AppBootstrapper..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at SMAStudiovNext.App.InitializeComponent()
   at SMAStudiovNext.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-08T18:16:53.915300800Z" />
    <EventRecordID>2000536</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TX60LP519681.na.wkglobal.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: SMAStudiovNext.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Gemini.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at Gemini.AppBootstrapper..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at SMAStudiovNext.App.InitializeComponent()
   at SMAStudiovNext.App.Main()

</Data>
  </EventData>
</Event>

**Comment by icanos** [comment]
Thanks for your report! I've been busy rewriting and updating some packages, could you please try to pull the latest code and compile and see if it works better? It works fine in my production env.

Let me know how it works out!

 / Marcus

**Comment by PatrickGallucci** [comment]
Works great now. Thanks!

**Comment by icanos** [comment]
Perfect, let me know if you run into anything else.
